# https://github.com/topiary/topiary/issues/1134
{
  languages = {
    bash.indent | priority 1 = "	",
    css.indent | priority 1 = "	",
    json.indent | priority 1 = "	",
    nickel.indent | priority 1 = "	",
    ocaml.indent | priority 1 = "	",
    ocaml_interface.indent | priority 1 = "	",
    ocamllex.indent | priority 1 = "	",
    rust.indent | priority 1 = "	",
    toml.indent | priority 1 = "	",
  },
}
