/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND_BANG = 1,
  anon_sym_LF = 2,
  sym_whitespace = 3,
  sym_interpreter_path = 4,
  aux_sym_interpreter_name_token1 = 5,
  sym_env_path = 6,
  sym_env_flags = 7,
  sym_args = 8,
  sym_script_content = 9,
  sym_source_file = 10,
  sym_shebang_line = 11,
  sym_direct_interpreter = 12,
  sym_interpreter_name = 13,
  sym_env_interpreter = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND_BANG] = "#!",
  [anon_sym_LF] = "\n",
  [sym_whitespace] = "whitespace",
  [sym_interpreter_path] = "interpreter_path",
  [aux_sym_interpreter_name_token1] = "interpreter_name_token1",
  [sym_env_path] = "env_path",
  [sym_env_flags] = "env_flags",
  [sym_args] = "args",
  [sym_script_content] = "script_content",
  [sym_source_file] = "source_file",
  [sym_shebang_line] = "shebang_line",
  [sym_direct_interpreter] = "direct_interpreter",
  [sym_interpreter_name] = "interpreter_name",
  [sym_env_interpreter] = "env_interpreter",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND_BANG] = anon_sym_POUND_BANG,
  [anon_sym_LF] = anon_sym_LF,
  [sym_whitespace] = sym_whitespace,
  [sym_interpreter_path] = sym_interpreter_path,
  [aux_sym_interpreter_name_token1] = aux_sym_interpreter_name_token1,
  [sym_env_path] = sym_env_path,
  [sym_env_flags] = sym_env_flags,
  [sym_args] = sym_args,
  [sym_script_content] = sym_script_content,
  [sym_source_file] = sym_source_file,
  [sym_shebang_line] = sym_shebang_line,
  [sym_direct_interpreter] = sym_direct_interpreter,
  [sym_interpreter_name] = sym_interpreter_name,
  [sym_env_interpreter] = sym_env_interpreter,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_interpreter_path] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_interpreter_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_env_path] = {
    .visible = true,
    .named = true,
  },
  [sym_env_flags] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_script_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_shebang_line] = {
    .visible = true,
    .named = true,
  },
  [sym_direct_interpreter] = {
    .visible = true,
    .named = true,
  },
  [sym_interpreter_name] = {
    .visible = true,
    .named = true,
  },
  [sym_env_interpreter] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == 'b') ADVANCE(10);
      if (lookahead == 'z') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(1);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == 'b') ADVANCE(10);
      if (lookahead == 'z') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == 'n') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == 'v') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(8);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'h') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(25);
      END_STATE();
    case 14:
      if (eof) ADVANCE(16);
      if (lookahead == '#') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_POUND_BANG);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_whitespace);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_whitespace);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_interpreter_path);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == 'e') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(9);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_interpreter_name_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_env_path);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(9);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_env_flags);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_args);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(26);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_args);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_script_content);
      if (lookahead == '!') ADVANCE(17);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_script_content);
      if (lookahead == '#') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_script_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_script_content);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 15},
  [13] = {.lex_state = 15},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 15},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND_BANG] = ACTIONS(1),
    [aux_sym_interpreter_name_token1] = ACTIONS(1),
    [sym_env_flags] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(37),
    [sym_shebang_line] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND_BANG] = ACTIONS(5),
    [sym_script_content] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(9), 1,
      sym_whitespace,
    ACTIONS(11), 1,
      sym_interpreter_path,
    ACTIONS(13), 1,
      sym_env_path,
    STATE(14), 1,
      sym_direct_interpreter,
  [13] = 4,
    ACTIONS(15), 1,
      sym_whitespace,
    ACTIONS(17), 1,
      aux_sym_interpreter_name_token1,
    ACTIONS(19), 1,
      sym_env_flags,
    STATE(19), 1,
      sym_env_interpreter,
  [26] = 4,
    ACTIONS(17), 1,
      aux_sym_interpreter_name_token1,
    ACTIONS(21), 1,
      sym_whitespace,
    ACTIONS(23), 1,
      sym_env_flags,
    STATE(25), 1,
      sym_env_interpreter,
  [39] = 3,
    ACTIONS(25), 1,
      sym_interpreter_path,
    ACTIONS(27), 1,
      sym_env_path,
    STATE(9), 1,
      sym_direct_interpreter,
  [49] = 3,
    ACTIONS(17), 1,
      aux_sym_interpreter_name_token1,
    ACTIONS(21), 1,
      sym_whitespace,
    STATE(25), 1,
      sym_env_interpreter,
  [59] = 3,
    ACTIONS(17), 1,
      aux_sym_interpreter_name_token1,
    ACTIONS(29), 1,
      sym_whitespace,
    STATE(21), 1,
      sym_env_interpreter,
  [69] = 2,
    ACTIONS(31), 1,
      aux_sym_interpreter_name_token1,
    STATE(11), 1,
      sym_interpreter_name,
  [76] = 2,
    ACTIONS(33), 1,
      anon_sym_LF,
    ACTIONS(35), 1,
      sym_args,
  [83] = 1,
    ACTIONS(37), 2,
      anon_sym_LF,
      sym_args,
  [88] = 1,
    ACTIONS(39), 2,
      anon_sym_LF,
      sym_args,
  [93] = 2,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym_script_content,
  [100] = 1,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [105] = 2,
    ACTIONS(47), 1,
      anon_sym_LF,
    ACTIONS(49), 1,
      sym_args,
  [112] = 1,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [117] = 2,
    ACTIONS(53), 1,
      aux_sym_interpreter_name_token1,
    STATE(25), 1,
      sym_env_interpreter,
  [124] = 2,
    ACTIONS(53), 1,
      aux_sym_interpreter_name_token1,
    STATE(21), 1,
      sym_env_interpreter,
  [131] = 1,
    ACTIONS(55), 2,
      anon_sym_LF,
      sym_args,
  [136] = 2,
    ACTIONS(57), 1,
      anon_sym_LF,
    ACTIONS(59), 1,
      sym_args,
  [143] = 1,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [148] = 2,
    ACTIONS(63), 1,
      anon_sym_LF,
    ACTIONS(65), 1,
      sym_args,
  [155] = 2,
    ACTIONS(53), 1,
      aux_sym_interpreter_name_token1,
    STATE(26), 1,
      sym_env_interpreter,
  [162] = 1,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [167] = 1,
    ACTIONS(69), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [172] = 2,
    ACTIONS(71), 1,
      anon_sym_LF,
    ACTIONS(73), 1,
      sym_args,
  [179] = 2,
    ACTIONS(75), 1,
      anon_sym_LF,
    ACTIONS(77), 1,
      sym_args,
  [186] = 1,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [191] = 1,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [196] = 1,
    ACTIONS(83), 1,
      anon_sym_LF,
  [200] = 1,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [204] = 1,
    ACTIONS(87), 1,
      sym_whitespace,
  [208] = 1,
    ACTIONS(89), 1,
      anon_sym_LF,
  [212] = 1,
    ACTIONS(91), 1,
      anon_sym_LF,
  [216] = 1,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
  [220] = 1,
    ACTIONS(93), 1,
      sym_whitespace,
  [224] = 1,
    ACTIONS(95), 1,
      anon_sym_LF,
  [228] = 1,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
  [232] = 1,
    ACTIONS(99), 1,
      anon_sym_LF,
  [236] = 1,
    ACTIONS(101), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 13,
  [SMALL_STATE(4)] = 26,
  [SMALL_STATE(5)] = 39,
  [SMALL_STATE(6)] = 49,
  [SMALL_STATE(7)] = 59,
  [SMALL_STATE(8)] = 69,
  [SMALL_STATE(9)] = 76,
  [SMALL_STATE(10)] = 83,
  [SMALL_STATE(11)] = 88,
  [SMALL_STATE(12)] = 93,
  [SMALL_STATE(13)] = 100,
  [SMALL_STATE(14)] = 105,
  [SMALL_STATE(15)] = 112,
  [SMALL_STATE(16)] = 117,
  [SMALL_STATE(17)] = 124,
  [SMALL_STATE(18)] = 131,
  [SMALL_STATE(19)] = 136,
  [SMALL_STATE(20)] = 143,
  [SMALL_STATE(21)] = 148,
  [SMALL_STATE(22)] = 155,
  [SMALL_STATE(23)] = 162,
  [SMALL_STATE(24)] = 167,
  [SMALL_STATE(25)] = 172,
  [SMALL_STATE(26)] = 179,
  [SMALL_STATE(27)] = 186,
  [SMALL_STATE(28)] = 191,
  [SMALL_STATE(29)] = 196,
  [SMALL_STATE(30)] = 200,
  [SMALL_STATE(31)] = 204,
  [SMALL_STATE(32)] = 208,
  [SMALL_STATE(33)] = 212,
  [SMALL_STATE(34)] = 216,
  [SMALL_STATE(35)] = 220,
  [SMALL_STATE(36)] = 224,
  [SMALL_STATE(37)] = 228,
  [SMALL_STATE(38)] = 232,
  [SMALL_STATE(39)] = 236,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpreter_name, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_direct_interpreter, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_env_interpreter, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 5, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 6, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 7, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 8, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 9, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [97] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_generic_shell(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
