/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 12
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND_BANG = 1,
  aux_sym_shebang_line_token1 = 2,
  anon_sym_LF = 3,
  sym_direct_interpreter = 4,
  sym_env_path = 5,
  sym_env_flags = 6,
  sym_env_interpreter = 7,
  sym_args = 8,
  sym_script_content = 9,
  sym_source_file = 10,
  sym_shebang_line = 11,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND_BANG] = "#!",
  [aux_sym_shebang_line_token1] = "shebang_line_token1",
  [anon_sym_LF] = "\n",
  [sym_direct_interpreter] = "direct_interpreter",
  [sym_env_path] = "env_path",
  [sym_env_flags] = "env_flags",
  [sym_env_interpreter] = "env_interpreter",
  [sym_args] = "args",
  [sym_script_content] = "script_content",
  [sym_source_file] = "source_file",
  [sym_shebang_line] = "shebang_line",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND_BANG] = anon_sym_POUND_BANG,
  [aux_sym_shebang_line_token1] = aux_sym_shebang_line_token1,
  [anon_sym_LF] = anon_sym_LF,
  [sym_direct_interpreter] = sym_direct_interpreter,
  [sym_env_path] = sym_env_path,
  [sym_env_flags] = sym_env_flags,
  [sym_env_interpreter] = sym_env_interpreter,
  [sym_args] = sym_args,
  [sym_script_content] = sym_script_content,
  [sym_source_file] = sym_source_file,
  [sym_shebang_line] = sym_shebang_line,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_shebang_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_direct_interpreter] = {
    .visible = true,
    .named = true,
  },
  [sym_env_path] = {
    .visible = true,
    .named = true,
  },
  [sym_env_flags] = {
    .visible = true,
    .named = true,
  },
  [sym_env_interpreter] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_script_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_shebang_line] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == 'b') ADVANCE(14);
      if (lookahead == 'z') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(1);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == 'b') ADVANCE(14);
      if (lookahead == 'z') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == 'a') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == 'b') ADVANCE(6);
      if (lookahead == 'e') ADVANCE(9);
      if (lookahead == 'z') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == 'h') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == 's') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == 'v') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(12);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(12);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'h') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(28);
      END_STATE();
    case 18:
      if (eof) ADVANCE(20);
      if (lookahead == '#') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND_BANG);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_shebang_line_token1);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(13);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_shebang_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_direct_interpreter);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(13);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_env_path);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(13);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_env_flags);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_env_interpreter);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_args);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_args);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_script_content);
      if (lookahead == '!') ADVANCE(21);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_script_content);
      if (lookahead == '#') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_script_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_script_content);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 19},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 19},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 19},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 19},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 19},
  [22] = {.lex_state = 19},
  [23] = {.lex_state = 19},
  [24] = {.lex_state = 19},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND_BANG] = ACTIONS(1),
    [sym_env_flags] = ACTIONS(1),
    [sym_env_interpreter] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym_shebang_line] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND_BANG] = ACTIONS(5),
    [sym_script_content] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(9), 1,
      aux_sym_shebang_line_token1,
    ACTIONS(11), 1,
      sym_direct_interpreter,
    ACTIONS(13), 1,
      sym_env_path,
  [10] = 3,
    ACTIONS(15), 1,
      aux_sym_shebang_line_token1,
    ACTIONS(17), 1,
      sym_env_flags,
    ACTIONS(19), 1,
      sym_env_interpreter,
  [20] = 3,
    ACTIONS(21), 1,
      aux_sym_shebang_line_token1,
    ACTIONS(23), 1,
      sym_env_flags,
    ACTIONS(25), 1,
      sym_env_interpreter,
  [30] = 3,
    ACTIONS(23), 1,
      sym_env_flags,
    ACTIONS(25), 1,
      sym_env_interpreter,
    ACTIONS(27), 1,
      aux_sym_shebang_line_token1,
  [40] = 3,
    ACTIONS(29), 1,
      aux_sym_shebang_line_token1,
    ACTIONS(31), 1,
      sym_env_flags,
    ACTIONS(33), 1,
      sym_env_interpreter,
  [50] = 1,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [55] = 2,
    ACTIONS(37), 1,
      anon_sym_LF,
    ACTIONS(39), 1,
      sym_args,
  [62] = 2,
    ACTIONS(41), 1,
      anon_sym_LF,
    ACTIONS(43), 1,
      sym_args,
  [69] = 2,
    ACTIONS(45), 1,
      anon_sym_LF,
    ACTIONS(47), 1,
      sym_args,
  [76] = 2,
    ACTIONS(25), 1,
      sym_env_interpreter,
    ACTIONS(27), 1,
      aux_sym_shebang_line_token1,
  [83] = 1,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [88] = 2,
    ACTIONS(29), 1,
      aux_sym_shebang_line_token1,
    ACTIONS(33), 1,
      sym_env_interpreter,
  [95] = 2,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym_script_content,
  [102] = 2,
    ACTIONS(55), 1,
      sym_direct_interpreter,
    ACTIONS(57), 1,
      sym_env_path,
  [109] = 1,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [114] = 2,
    ACTIONS(61), 1,
      aux_sym_shebang_line_token1,
    ACTIONS(63), 1,
      sym_env_interpreter,
  [121] = 2,
    ACTIONS(65), 1,
      anon_sym_LF,
    ACTIONS(67), 1,
      sym_args,
  [128] = 2,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(71), 1,
      sym_args,
  [135] = 2,
    ACTIONS(73), 1,
      anon_sym_LF,
    ACTIONS(75), 1,
      sym_args,
  [142] = 1,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [147] = 1,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [152] = 1,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [157] = 1,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      sym_script_content,
  [162] = 1,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [166] = 1,
    ACTIONS(87), 1,
      anon_sym_LF,
  [170] = 1,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
  [174] = 1,
    ACTIONS(91), 1,
      anon_sym_LF,
  [178] = 1,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
  [182] = 1,
    ACTIONS(93), 1,
      sym_env_interpreter,
  [186] = 1,
    ACTIONS(95), 1,
      sym_env_interpreter,
  [190] = 1,
    ACTIONS(97), 1,
      sym_env_interpreter,
  [194] = 1,
    ACTIONS(99), 1,
      anon_sym_LF,
  [198] = 1,
    ACTIONS(101), 1,
      anon_sym_LF,
  [202] = 1,
    ACTIONS(103), 1,
      anon_sym_LF,
  [206] = 1,
    ACTIONS(105), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 10,
  [SMALL_STATE(4)] = 20,
  [SMALL_STATE(5)] = 30,
  [SMALL_STATE(6)] = 40,
  [SMALL_STATE(7)] = 50,
  [SMALL_STATE(8)] = 55,
  [SMALL_STATE(9)] = 62,
  [SMALL_STATE(10)] = 69,
  [SMALL_STATE(11)] = 76,
  [SMALL_STATE(12)] = 83,
  [SMALL_STATE(13)] = 88,
  [SMALL_STATE(14)] = 95,
  [SMALL_STATE(15)] = 102,
  [SMALL_STATE(16)] = 109,
  [SMALL_STATE(17)] = 114,
  [SMALL_STATE(18)] = 121,
  [SMALL_STATE(19)] = 128,
  [SMALL_STATE(20)] = 135,
  [SMALL_STATE(21)] = 142,
  [SMALL_STATE(22)] = 147,
  [SMALL_STATE(23)] = 152,
  [SMALL_STATE(24)] = 157,
  [SMALL_STATE(25)] = 162,
  [SMALL_STATE(26)] = 166,
  [SMALL_STATE(27)] = 170,
  [SMALL_STATE(28)] = 174,
  [SMALL_STATE(29)] = 178,
  [SMALL_STATE(30)] = 182,
  [SMALL_STATE(31)] = 186,
  [SMALL_STATE(32)] = 190,
  [SMALL_STATE(33)] = 194,
  [SMALL_STATE(34)] = 198,
  [SMALL_STATE(35)] = 202,
  [SMALL_STATE(36)] = 206,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 4, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 5, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 7, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 8, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 6, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shebang_line, 9, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_shell_shebang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
