# Minimal Windows workflow

on:
  pull_request:
    branches:
      - main

jobs:
  windows:
    # Note: GitHub's Windows runners have a Rust toolchain installed
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test suite
        shell: bash
        run: |
          export CC="$(which gcc)"
          export CCX="${CC}"
          cargo test --all-features
