name: Build cache and tooling

description: Unix os build cache and linker

inputs:
  nix_path:
    description: the nix channel to use
    required: true
  auth_token:
    description: CACHIX auth token
    required: true

runs:
  using: "composite"
  steps:
  - name: Install Nix
    uses: cachix/install-nix-action@v31
    with:
      nix_path: ${{ inputs.nix_path }}

  - name: Setup up mold linker
    uses: rui314/setup-mold@v1

  - name: Set up Nix cache
    uses: cachix/cachix-action@v16
    with:
      name: tweag-topiary
      authToken: "${{ input.auth_token }}"

  - name: Set up frontend cache
    uses: actions/cache@v4
    with:
      path: |
        **/node_modules
        ~/.cache/puppeteer
      key: frontend_${{ matrix.os }}_${{ hashFiles('**/package-lock.json') }}
